apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn-config
data:
  turnserver.conf: |
    tls-listening-port=443
    listening-port=443
    no-udp
    cert=/etc/coturn/tls/tls.crt
    pkey=/etc/coturn/tls/tls.key
    fingerprint
    lt-cred-mech
    realm=floriantoenjes.com
    user=<username>:<password>
    external-ip=<external-ip>/<internal-svc-ip>
    no-ipv6
    verbose