apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: coturn-backend-config
spec:
  healthCheck:
    type: HTTP
    checkIntervalSec: 30
    timeoutSec: 10
    port: 8080
    requestPath: /health
    healthyThreshold: 1
    unhealthyThreshold: 3