apiVersion: v1
kind: Service
metadata:
  name: coturn
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "coturn-backend-config"}'
spec:
  selector:
    app: coturn
  ports:
    - port: 443
      targetPort: 443
      name: turn
  type: ClusterIP