apiVersion: apps/v1
kind: Deployment
metadata:
  name: coturn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coturn
  template:
    metadata:
      labels:
        app: coturn
    spec:
      containers:
        - name: coturn
          image: instrumentisto/coturn:latest
          ports:
            - containerPort: 443
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coturn
            - name: tls-cert
              mountPath: "/etc/coturn/tls"   # Path in the container to mount the certificate files
              readOnly: true
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          command: [ "/bin/sh", "-c" ]
          args:
            - echo 'server { listen 8080; location /health { return 200 "OK"; add_header Content-Type text/plain; } }' > /etc/nginx/conf.d/health.conf && nginx -g 'daemon off;'
      volumes:
        - name: config-volume
          configMap:
            name: coturn-config
        - name: tls-cert
          secret:
            secretName: turn-tls-secret