apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0.13-jammy
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              protocol: TCP
      restartPolicy: Always


