apiVersion: v1
kind: Service
metadata:
  name: coturn-health
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"default": "coturn-backend-config"}'
spec:
  selector:
    app: coturn
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP