apiVersion: v1
kind: Service
metadata:
  name: realtime-chat
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "ws-backend-config"}'
spec:
  selector:
    app: realtime-chat
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: ClusterIP
