apiVersion: v1
kind: Service
metadata:
  name: realtime-chat-peer-server
spec:
  selector:
    app: realtime-chat
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
