apiVersion: v1
kind: Service
metadata:
  name: realtime-chat
spec:
  selector:
    app: realtime-chat
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: LoadBalancer
  externalIPs:
    - 192.168.2.200

