apiVersion: v1
kind: Service
metadata:
  name: realtime-chat-peer-server
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "ws-backend-config"}'
spec:
  selector:
    app: realtime-chat
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
