apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3mock
  labels:
    app: s3mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3mock
  template:
    metadata:
      name: s3mock
      labels:
        app: s3mock
    spec:
      containers:
        - name: s3-mock
          image: adobe/s3mock:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: initialBuckets
              value: "florians-realtime-chat-bucket"
          ports:
            - containerPort: 9090
              protocol: TCP
      restartPolicy: Always


