name: Release
on:
  push:

jobs:
  docker-release:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')  # <-- Notice that I'm filtering here to only run when a tagged commit is pushed

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GOOGLE_AUTH }}
          service_account: my-service-account@my-project-1470767799419.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            europe-west3-docker.pkg.dev/my-project-1470767799419/realtime-chat-repo/realtime-chat-gke:${{ steps.get-tag.outputs.short_ref }}
            europe-west3-docker.pkg.dev/my-project-1470767799419/realtime-chat-repo/realtime-chat-gke:latest
          build-args: |
            VITE_PEERJS_SERVER_HOST=${{ secrets.VITE_PEERJS_SERVER_HOST }}
            VITE_PEERJS_SERVER_PORT=${{ secrets.VITE_PEERJS_SERVER_PORT }}
            VITE_TURN_SERVER_URL=${{ secrets.VITE_TURN_SERVER_URL }}
            VITE_TURN_SERVER_USERNAME=${{ secrets.VITE_TURN_SERVER_USERNAME }}
            VITE_TURN_SERVER_PASSWORD=${{ secrets.VITE_TURN_SERVER_PASSWORD }}

      - name: Set up kubectl
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: my-project-1470767799419

      - name: 'Install gke-gcloud-auth-plugin'
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gke-gcloud-auth-plugin --version

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project my-project-1470767799419

      - name: Update Kubernetes deployment with new annotation
        env:
          KUBE_DEPLOYMENT: "realtime-chat"
        run: |
          kubectl patch deployment $KUBE_DEPLOYMENT -p \
            "{\"spec\": {\"template\": {\"metadata\": {\"annotations\": {\"lastUpdated\": \"$(date +'%s')\"}}}}}"